import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import Header from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
          {/* <SidebarProvider className='font-sans'>
            <AppSidebar />
            <SidebarInset>
              <Header />
              <div className='w-full py-6 max-w-7xl mx-auto flex flex-1 flex-col gap-4 p-8'> */}
          {children}
          {/* </div>
            </SidebarInset>
          </SidebarProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
